//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.CpuLimiter.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Avalonia.CpuLimiter.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
    public static string FileButton
    {
        get { return ResourceManager.GetString("FileButton", resourceCulture); }
    }

    public static string EditButton
    {
        get { return ResourceManager.GetString("EditButton", resourceCulture); }
    }

    public static string HelpButton
    {
        get { return ResourceManager.GetString("HelpButton", resourceCulture); }
    }

    public static string RunButton
    {
        get { return ResourceManager.GetString("RunButton", resourceCulture); }
    }

    public static string SettingButton
    {
        get { return ResourceManager.GetString("SettingButton", resourceCulture); }
    }

    public static string LaunchButton
    {
        get { return ResourceManager.GetString("LaunchButton", resourceCulture); }
    }

    public static string CPUCoreNumberTextBlock
    {
        get { return ResourceManager.GetString("CPUCoreNumberTextBlock", resourceCulture); }
    }

    public static string OpenButton
    {
        get { return ResourceManager.GetString("OpenButton", resourceCulture); }
    }

    public static string SaveButton
    {
        get { return ResourceManager.GetString("SaveButton", resourceCulture); }
    }

    public static string ExitButton
    {
        get { return ResourceManager.GetString("ExitButton", resourceCulture); }
    }

    public static string CutButton
    {
        get { return ResourceManager.GetString("CutButton", resourceCulture); }
    }

    public static string CopyButton
    {
        get { return ResourceManager.GetString("CopyButton", resourceCulture); }
    }

    public static string PasteButton
    {
        get { return ResourceManager.GetString("PasteButton", resourceCulture); }
    }

    public static string ThemeSwitch
    {
        get { return ResourceManager.GetString("ThemeSwitch", resourceCulture); }
    }

    public static string ConfigButton
    {
        get { return ResourceManager.GetString("ConfigButton", resourceCulture); }
    }

    public static string DocsButton
    {
        get { return ResourceManager.GetString("DocsButton", resourceCulture); }
    }

    public static string ProjButton
    {
        get { return ResourceManager.GetString("ProjButton", resourceCulture); }
    }

    public static string AboutButton
    {
        get { return ResourceManager.GetString("AboutButton", resourceCulture); }
    }

    public static string LaunchGameButton
    {
        get { return ResourceManager.GetString("LaunchGameButton", resourceCulture); }
    }
    public static string ExeFileBlock
    {
        get { return ResourceManager.GetString("ExeFileBlock", resourceCulture); }
    }
    public static string LightThemeButton
    {
        get { return ResourceManager.GetString("LightThemeButton", resourceCulture); }
    }
    public static string DarkThemeButton
    {
        get { return ResourceManager.GetString("DarkThemeButton", resourceCulture); }
    }
    public static string CopyCloseButton
    {
        get { return ResourceManager.GetString("CopyCloseButton", resourceCulture); }
    }
    public static string CloseButton
    {
        get { return ResourceManager.GetString("CloseButton", resourceCulture); }
    }
    public static string LanguageSwitch
    {
        get { return ResourceManager.GetString("LanguageSwitch", resourceCulture); }
    }
    public static string SettingStartupLanguageToggleEnglish
    {
        get { return ResourceManager.GetString("SettingStartupLanguageToggleEnglish", resourceCulture); }
    }

    public static string SettingStartupLanguageToggleChinese
    {
        get { return ResourceManager.GetString("SettingStartupLanguageToggleChinese", resourceCulture); }
    }

    public static string SettingStartupThemeTextBlock
    {
        get { return ResourceManager.GetString("SettingStartupThemeTextBlock", resourceCulture); }
    }

    public static string StartupDecorationSliderTextBlock
    {
        get { return ResourceManager.GetString("StartupDecorationSliderTextBlock", resourceCulture); }
    }

    public static string SettingHistoryLimitTextBlock
    {
        get { return ResourceManager.GetString("SettingHistoryLimitTextBlock", resourceCulture); }
    }

    public static string SettingThemeColorSliderTextBlock
    {
        get { return ResourceManager.GetString("SettingThemeColorSliderTextBlock", resourceCulture); }
    } 
    public static string SettingTitle
    {
        get { return ResourceManager.GetString("SettingTitle", resourceCulture); }
    }
    public static string FilePickerTitle
    {
        get { return ResourceManager.GetString("FilePickerTitle", resourceCulture); }
    }
    public static string SaveFilePickerTitle
    {
        get { return ResourceManager.GetString("SaveFilePickerTitle", resourceCulture); }
    }
    public static string AboutAuthorText
    {
        get { return ResourceManager.GetString("AboutAuthorText", resourceCulture); }
    }

    public static string AboutDotnetVersionText
    {
        get { return ResourceManager.GetString("AboutDotnetVersionText", resourceCulture); }
    }

    public static string AvaloniaUIVersionText
    {
        get { return ResourceManager.GetString("AvaloniaUIVersionText", resourceCulture); }
    }

    public static string AboutLicenseText
    {
        get { return ResourceManager.GetString("AboutLicenseText", resourceCulture); }
    } 
    public static string TrayOpenFileButton
    {
        get { return ResourceManager.GetString("TrayOpenFileButton", resourceCulture); }
    }

    public static string TrayRestoreButton
    {
        get { return ResourceManager.GetString("TrayRestoreButton", resourceCulture); }
    }

    public static string TrayLaunchButton
    {
        get { return ResourceManager.GetString("TrayLaunchButton", resourceCulture); }
    }

    public static string TrayOpenSettingButton
    {
        get { return ResourceManager.GetString("TrayOpenSettingButton", resourceCulture); }
    }

    public static string TrayExitButton
    {
        get { return ResourceManager.GetString("TrayExitButton", resourceCulture); }
    }    
    }
}
