//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.CpuLimiter.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Avalonia.CpuLimiter.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
    public static string FileButton
    {
        get { return ResourceManager.GetString("FileButton", resourceCulture); }
    }

    public static string EditButton
    {
        get { return ResourceManager.GetString("EditButton", resourceCulture); }
    }

    public static string HelpButton
    {
        get { return ResourceManager.GetString("HelpButton", resourceCulture); }
    }

    public static string RunButton
    {
        get { return ResourceManager.GetString("RunButton", resourceCulture); }
    }

    public static string SettingButton
    {
        get { return ResourceManager.GetString("SettingButton", resourceCulture); }
    }

    public static string LaunchButton
    {
        get { return ResourceManager.GetString("LaunchButton", resourceCulture); }
    }

    public static string CPUCoreNumberTextBlock
    {
        get { return ResourceManager.GetString("CPUCoreNumberTextBlock", resourceCulture); }
    }

    public static string OpenButton
    {
        get { return ResourceManager.GetString("OpenButton", resourceCulture); }
    }

    public static string SaveButton
    {
        get { return ResourceManager.GetString("SaveButton", resourceCulture); }
    }

    public static string ExitButton
    {
        get { return ResourceManager.GetString("ExitButton", resourceCulture); }
    }

    public static string CutButton
    {
        get { return ResourceManager.GetString("CutButton", resourceCulture); }
    }

    public static string CopyButton
    {
        get { return ResourceManager.GetString("CopyButton", resourceCulture); }
    }

    public static string PasteButton
    {
        get { return ResourceManager.GetString("PasteButton", resourceCulture); }
    }

    public static string ThemeSwitch
    {
        get { return ResourceManager.GetString("ThemeSwitch", resourceCulture); }
    }

    public static string ConfigButton
    {
        get { return ResourceManager.GetString("ConfigButton", resourceCulture); }
    }

    public static string DocsButton
    {
        get { return ResourceManager.GetString("DocsButton", resourceCulture); }
    }

    public static string ProjButton
    {
        get { return ResourceManager.GetString("ProjButton", resourceCulture); }
    }

    public static string AboutButton
    {
        get { return ResourceManager.GetString("AboutButton", resourceCulture); }
    }

    public static string LaunchGameButton
    {
        get { return ResourceManager.GetString("LaunchGameButton", resourceCulture); }
    }
    public static string ExeFileBlock
    {
        get { return ResourceManager.GetString("ExeFileBlock", resourceCulture); }
    }
     public static string LightThemeButton
    {
        get { return ResourceManager.GetString("LightThemeButton", resourceCulture); }
    }
     public static string DarkThemeButton
    {
        get { return ResourceManager.GetString("DarkThemeButton", resourceCulture); }
    }
     public static string CopyCloseButton
    {
        get { return ResourceManager.GetString("CopyCloseButton", resourceCulture); }
    }
      public static string CloseButton
    {
        get { return ResourceManager.GetString("CloseButton", resourceCulture); }
    }
      public static string LanguageSwitch
    {
        get { return ResourceManager.GetString("LanguageSwitch", resourceCulture); }
    }
        
    }
}
